### ISSUE TITLE
[Request] sleepgraph: add firmware times to summaries

### ISSUE THREAD

**Issue by thac0** [intel/pm-graph#12]
As it stands in v5.3, the default _summary.html_ will omit firmware suspend and resume times and not factor them into the total times. While that's sufficient for kernel-focused development-- where firmware is assumed to be a "black box"-- it's not ideal from a platform perspective. Would like to be able to see those firmware numbers in the _summary_ outputs from sleepgraph.

**Comment by tebrandt** [comment]
I was thinking about adding this, I just created a bugzilla enhancement request for it:
https://bugzilla.kernel.org/show_bug.cgi?id=203919

P.S. bugzilla.kernel.org is the quicker way to file issues, I only rarely check the github issues area.
