### ISSUE TITLE
DEVMEM: "no legitimate users anymore", unsafe dependency for pm-graph tools

### ISSUE THREAD

**Issue by thac0** [intel/pm-graph#13]
In Clear Linux, DEVMEM is considered a Bad Thing, with "no legitimate users anymore". So, requesting that pm-graph's tools not use DEVMEM at all for gathering platform information (and firmware time during resume, right?).

Discussion being held over here:
https://github.com/clearlinux/distribution/issues/863#issuecomment-499707750

**Comment by tebrandt** [comment]
Well it's just FPDT and DMI data, what are the preferred alternatives? I know that the dmidecode app has it's own UEFI method (which I need to support), but for FPDT I don't know how else to grab it.

**Comment by thac0** [comment]
Systemd gleans boot time from FPDT this way:
* https://github.com/systemd/systemd/blob/6e2f78948403a4cce45b9e34311c9577c624f066/src/shared/acpi-fpdt.c#L64

**Comment by thac0** [comment]
I (naively) assumed there was an alternative ready-to-hand for accessing FPDT info. 15 minutes of searching has challenged that assumption. I'll dig a bit deeper.

**Comment by tebrandt** [comment]
A patch was added back in Jan of 2021 that put the FPDT in /sys/firmware/acpi/FPDT. I acked it. The sleepgraph tool now starts by using that, but if it doesn't exist (e.g. it's an older kernel) it defaults back to using /dev/mem if available. So this issue should be resolved.
