### ISSUE TITLE
kprobes: scrutinze pm-graph's usage of them, and look into adding (more) tracepoints upstream in, say, msleep()

### ISSUE THREAD

**Issue by thac0** [intel/pm-graph#14]
Title speaks for itself. I'm exploring ways for pm-graph to get at information "-dev" mode needs without resorting to kprobes. This is because Clear Linux will not ship a kernel with Kprobes enabled (for security reasons). I'd like pm-graph to be able to run, e.g. sleepgraph, out-of-the-box without requiring the user to re-build a kernel.

**Comment by tebrandt** [comment]
kprobes are the only way to get argument data, but if all you care about is function calls you can just use -f. It will generate a full callgraph trace of all the device callbacks. You can also use -ftop to gather a trace just of the suspend_devices_and_enter call (which includes all the platform code).
