### ISSUE TITLE
TypeError: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by matschi-klickme** [intel/pm-graph#15]
Hey there, 
I get errors when trying to run. 
Thanks for your time and effort!  

> uname -a
> Linux errors 5.4.17-1-MANJARO #1 SMP PREEMPT Tue Feb 4 11:40:50 UTC 2020 x86_64 GNU/Linux

> python -V
> Python 3.8.1

> [errors pm-graph]# ./analyze_suspend.py 
> Checking this system (errors)...
>     have root access: YES
>     is sysfs mounted: YES
>     is "mem" a valid power mode: YES
>     is ftrace supported: YES
>     are kprobes supported: YES
>     timeline data source: FTRACE (all trace events found)
>     is rtcwake supported: YES
> baseboard-manufacturer  : LENOVO
> baseboard-product-name  : 20HN002UGE
> baseboard-serial-number : L2HF78T06SE
> baseboard-version       : SDK0J40697 WIN
> bios-release-date       : 09/26/2019
> bios-vendor             : LENOVO
> bios-version            : R0IET59W (1.37 )
> chassis-manufacturer    : LENOVO
> chassis-serial-number   : PC0Q1PKX
> chassis-version         : None
> processor-manufacturer  : Intel(R) Corporation
> processor-version       : Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
> system-manufacturer     : LENOVO
> system-product-name     : 20HN002UGE
> system-serial-number    : PC0Q1PKX
> system-version          : ThinkPad X270
> cpucount                : 4
> memtotal                : 16159280 kB
> memfree                 : 11117064 kB
> INITIALIZING FTRACE...
> INITIALIZING KPROBES...
> START TRACING
> SUSPEND START
> will issue an rtcwake in 15 seconds
> RESUME COMPLETE
> Traceback (most recent call last):
>   File "./analyze_suspend.py", line 6763, in <module>
>     ret = runTest()
>   File "./analyze_suspend.py", line 5904, in runTest
>     executeSuspend()
>   File "./analyze_suspend.py", line 5237, in executeSuspend
>     cmdafter = sysvals.cmdinfo(False)
>   File "./analyze_suspend.py", line 1044, in cmdinfo
>     prefix = self.commonPrefix(before.keys())
>   File "./analyze_suspend.py", line 998, in commonPrefix
>     prefix = list[0]
> TypeError: 'dict_keys' object is not subscriptable
>

**Comment by tebrandt** [comment]
I'll take a look, thanks for the feedback.

**Comment by tebrandt** [comment]
I think it's fixed, I use list() now since python3 dict.keys() are only iterable.

https://github.com/intel/pm-graph/commit/7804ba9e5139f083ac8796f38edbc5a691b1510a

**Comment by matschi-klickme** [comment]
Works like a charm - thx! :) 

> INITIALIZING FTRACE...
> INITIALIZING KPROBES...
> START TRACING
> SUSPEND START
> will issue an rtcwake in 15 seconds
> RESUME COMPLETE
> CAPTURING DMESG
> CAPTURING TRACE
> PROCESSING DATA
> DONE
>
