### ISSUE TITLE
why the kernel time from pm-graph is dirrerent from the time of "systemd-analyze"

### ISSUE THREAD

**Issue by zhangming-cloud** [intel/pm-graph#21]
![图片](https://user-images.githubusercontent.com/62131507/127587767-6715b5ce-7c1b-4df3-b5b4-bd270b44da7a.png)
![图片](https://user-images.githubusercontent.com/62131507/127587847-072d1b03-787f-4c21-a74e-49f26305e2d0.png)

**Comment by tebrandt** [comment]
bootgraph is focused on the kernel time alone. The time from boot to the start of the init process is how we define the "kernel boot time". The init process is the start of "user space" which takes additional time to load, systemd has to wait until all of user space is loaded and its process has started, so its number includes kernel boot time plus its own user space start time.
