### ISSUE TITLE
Log is gone when system crashed

### ISSUE THREAD

**Issue by atar-axis** [intel/pm-graph#22]
I am trying to debug the sleep mode on my ThinkBook 13s-IWL. Unfortunately the system is crashing every once in a while.
The problem is, when the system is crashing, then nearly nothing is written to the log, therefore I cannot debug it. I just have no clue what happens.

Is there a way to rescue the data or write it immediately to the file?

**My situation is the following - just in case you are interested:**

From time to time, when I try to suspend the system to memory, the following happens:
the display turns black as expected,  the key lights turn off and everything else looks good, too.
Except for the power button which is not going into the slowly flashing mode. It stays on for a while, like a minute or so, then the laptop simply reboots.
I already reinstalled the UEFI and tried different settings, but the problem stays the same

**Comment by tebrandt** [comment]
You're experiencing the most common issue wrt debugging crashes, how to grab a log. The best way is to use a serial console (via USB-serial adapter) and configure the kernel to print debug info to the console up to the very end. You can dial into the console from another machine and monitor the log info. 

The quick way is to try and recover the last boot's dmnesg log. The dmesg log itself is usually stored in /var/log/kern.log.*. The system automatically renames the last log to kern.log.N after the next boot. You can see if there's any data in there prior to the crash.

**Comment by atar-axis** [comment]
I already thought about the serial console solution but I wasn't sure, because I would have expected that  the USB controller is also sent to sleep mode, isn't it?

Unfortunately there is no such file, or, to be more precise, it is empty.

**Comment by tebrandt** [comment]
you can add no_console_suspend to the kernel command line to be sure the console stays online during suspend.
