### ISSUE TITLE
How to get callgraph for `intel-lpss` and `nvme`?

### ISSUE THREAD

**Issue by paulmenzel** [intel/pm-graph#4]
Running `sudo ./analyze_suspend.py -config config/suspend-callgraph.cfg -filter intel-lpss` or `-filter "intel-lpss,nvme` on the Dell XPS13 9360, no callgraph is created, despite both or listed in the HTML file generated by `sudo ./analyze_suspend.py -m mem`.

Linux 4.10-rc7+ is used.

**Comment by tebrandt** [comment]
never got to this one, sorry, bugzilla.kernel.org is the primary bug site. if it's still an issue please re-open
