### ISSUE TITLE
Linux option `initcall_debug` also needed on recent Linux kernels for callgraph

### ISSUE THREAD

**Issue by paulmenzel** [intel/pm-graph#8]
The documentation claims that the option `initcall_debug` for a callgraph is only needed for Linux versions older than 3.15.0.

> If you're using a kernel older than 3.15.0, the following
>         additional kernel parameters are required:
>         (e.g. in file /etc/default/grub)
>         GRUB_CMDLINE_LINUX_DEFAULT="... initcall_debug log_buf_len=32M ..."

But at least with Linux 4.15.0 without that option no callgraph is displayed in the HTML file.

**Comment by tebrandt** [comment]
callgraph is taken entirely from ftrace, initcall_debug is only used for dmesg only timelines, it's essentially useless if ftrace is available.

**Comment by tebrandt** [comment]
oh wait, this applies to bootgraph, bootgraph always needs initcall_debug, I've updated the README
