### ISSUE TITLE
Python 3 support 

### ISSUE THREAD

**Issue by vrruiz** [intel/pm-graph#9]
As you may know, Python 2.7 is ending support on 2020, currently 1 year and 8 months away. Major Linux distros will stop supporting it as well, so migration to Python 3 is recommended.

I did a quick test using 2to3 script and print calls are fixed, but there is a change in the way popen is handled in Python 3 that prevents sleepgraph.py from working correctly.

**Comment by tebrandt** [comment]
I'm in the process of making it all python version compatible, should be done in a couple weeks.
